/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125953-gd3ad8a7fee-20260803"
#endif /* AVUTIL_FFVERSION_H */
